<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MHMunicipio extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $values = [
            [
                'codigo' => '00',
                'valor' => 'Otro País',
                'departamento' => '00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 01
            [
                'codigo' => '01',
                'valor' => 'AHUACHAPÁN',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'APANECA',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'ATIQUIZAYA',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'CONCEPCIÓN DE ATACO',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'EL REFUGIO',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'GUAYMANGO',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'JUJUTLA',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'SAN FRANCISCO MENÉNDEZ',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'SAN LORENZO',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'SAN PEDRO PUXTLA',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'TACUBA',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'TURÍN',
                'departamento' => '01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 02
            [
                'codigo' => '01',
                'valor' => 'CANDELARIA DE LA FRONTERA',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'COATEPEQUE',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'CHALCHUAPA',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'EL CONGO',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'EL PORVENIR',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'MASAHUAT',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'METAPÁN',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'SAN ANTONIO PAJONAL',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'SAN SEBASTIÁN SALITRILLO',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'SANTA ANA',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'STA ROSA GUACHI',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'STGO D LA FRONT',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'TEXISTEPEQUE',
                'departamento' => '02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 03
            [
                'codigo' => '01',
                'valor' => 'ACAJUTLA',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'ARMENIA',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'CALUCO',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'CUISNAHUAT',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'STA I ISHUATAN',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'IZALCO',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'JUAYÚA',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'NAHUIZALCO',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'NAHULINGO',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'SALCOATITÁN',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'SAN ANTONIO DEL MONTE',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'SAN JULIÁN',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'STA C MASAHUAT',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'SANTO DOMINGO GUZMÁN',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'SONSONATE',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'SONZACATE',
                'departamento' => '03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 04
            [
                'codigo' => '01',
                'valor' => 'AGUA CALIENTE',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'ARCATAO',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'AZACUALPA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'CITALÁ',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'COMALAPA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'CONCEPCIÓN QUEZALTEPEQUE',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'CHALATENANGO',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'DULCE NOM MARÍA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'EL CARRIZAL',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'EL PARAÍSO',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'LA LAGUNA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'LA PALMA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'LA REINA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'LAS VUELTAS',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'NOMBRE DE JESUS',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'NVA CONCEPCIÓN',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17',
                'valor' => 'NUEVA TRINIDAD',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18',
                'valor' => 'OJOS DE AGUA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '19',
                'valor' => 'POTONICO',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '20',
                'valor' => 'SAN ANT LA CRUZ',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '21',
                'valor' => 'SAN ANT RANCHOS',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '22',
                'valor' => 'SAN FERNANDO',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '23',
                'valor' => 'SAN FRANCISCO LEMPA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '24',
                'valor' => 'SAN FRANCISCO MORAZÁN',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '25',
                'valor' => 'SAN IGNACIO',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '26',
                'valor' => 'SAN I LABRADOR',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '27',
                'valor' => 'SAN J CANCASQUE',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '28',
                'valor' => 'SAN JOSE FLORES',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '29',
                'valor' => 'SAN LUIS CARMEN',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '30',
                'valor' => 'SN MIG MERCEDES',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '31',
                'valor' => 'SAN RAFAEL',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '32',
                'valor' => 'SANTA RITA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '33',
                'valor' => 'TEJUTLA',
                'departamento' => '04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 05
            [
                'codigo' => '01',
                'valor' => 'ANTGO CUSCATLÁN',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'CIUDAD ARCE',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'COLON',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'COMASAGUA',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'CHILTIUPAN',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'HUIZÚCAR',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'JAYAQUE',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'JICALAPA',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'LA LIBERTAD',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'NUEVO CUSCATLÁN',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'SANTA TECLA',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'QUEZALTEPEQUE',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'SACACOYO',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'SN J VILLANUEVA',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'SAN JUAN OPICO',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'SAN MATÍAS',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17',
                'valor' => 'SAN P TACACHICO',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18',
                'valor' => 'TAMANIQUE',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '19',
                'valor' => 'TALNIQUE',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '20',
                'valor' => 'TEOTEPEQUE',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '21',
                'valor' => 'TEPECOYO',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '22',
                'valor' => 'ZARAGOZA',
                'departamento' => '05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 06
            [
                'codigo' => '01',
                'valor' => 'AGUILARES',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'APOPA',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'AYUTUXTEPEQUE',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'CUSCATANCINGO',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'EL PAISNAL',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'GUAZAPA',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'ILOPANGO',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'MEJICANOS',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'NEJAPA',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'PANCHIMALCO',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'ROSARIO DE MORA',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'SAN MARCOS',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'SAN MARTIN',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'SAN SALVADOR',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'STG TEXACUANGOS',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'SANTO TOMAS',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17',
                'valor' => 'SOYAPANGO',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18',
                'valor' => 'TONACATEPEQUE',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '19',
                'valor' => 'CIUDAD DELGADO',
                'departamento' => '06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 07
            [
                'codigo' => '01',
                'valor' => 'CANDELARIA',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'COJUTEPEQUE',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'EL CARMEN',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'EL ROSARIO',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'MONTE SAN JUAN',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'ORAT CONCEPCIÓN',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'SAN B PERULAPIA',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'SAN CRISTÓBAL',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'SAN J GUAYABAL',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'SAN P PERULAPÁN',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'SAN RAF CEDROS',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'SAN RAMON',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'STA C ANALQUITO',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'STA C MICHAPA',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'SUCHITOTO',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'TENANCINGO',
                'departamento' => '07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 08
            [
                'codigo' => '01',
                'valor' => 'CUYULTITÁN',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'EL ROSARIO',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'JERUSALÉN',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'MERCED LA CEIBA',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'OLOCUILTA',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'PARAÍSO OSORIO',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'SN ANT MASAHUAT',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'SAN EMIGDIO',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'SN FCO CHINAMEC',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'SAN J NONUALCO',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'SAN JUAN TALPA',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'SAN JUAN TEPEZONTES',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'SAN LUIS TALPA',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'SAN MIGUEL TEPEZONTES',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'SAN PEDRO MASAHUAT',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'SAN PEDRO NONUALCO',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17',
                'valor' => 'SAN R OBRAJUELO',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18',
                'valor' => 'STA MA OSTUMA',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '19',
                'valor' => 'STGO NONUALCO',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '20',
                'valor' => 'TAPALHUACA',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '21',
                'valor' => 'ZACATECOLUCA',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '22',
                'valor' => 'SN LUIS LA HERR',
                'departamento' => '08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 09
            [
                'codigo' => '01',
                'valor' => 'CINQUERA',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'GUACOTECTI',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'ILOBASCO',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'JUTIAPA',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'SAN ISIDRO',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'SENSUNTEPEQUE',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'TEJUTEPEQUE',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'VICTORIA',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'DOLORES',
                'departamento' => '09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 10
            [
                'codigo' => '01',
                'valor' => 'APASTEPEQUE',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'GUADALUPE',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'SAN CAY ISTEPEQ',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'SANTA CLARA',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'SANTO DOMINGO',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'SN EST CATARINA',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'SAN ILDEFONSO',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'SAN LORENZO',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'SAN SEBASTIÁN',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'SAN VICENTE',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'TECOLUCA',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'TEPETITÁN',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'VERAPAZ',
                'departamento' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 11
            [
                'codigo' => '01',
                'valor' => 'ALEGRÍA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'BERLÍN',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'CALIFORNIA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'CONCEP BATRES',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'EL TRIUNFO',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'EREGUAYQUÍN',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'ESTANZUELAS',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'JIQUILISCO',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'JUCUAPA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'JUCUARÁN',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'MERCEDES UMAÑA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'NUEVA GRANADA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'OZATLÁN',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'PTO EL TRIUNFO',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'SAN AGUSTÍN',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'SN BUENAVENTURA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17',
                'valor' => 'SAN DIONISIO',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18',
                'valor' => 'SANTA ELENA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '19',
                'valor' => 'SAN FCO JAVIER',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '20',
                'valor' => 'SANTA MARÍA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '21',
                'valor' => 'STGO DE MARÍA',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '22',
                'valor' => 'TECAPÁN',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '23',
                'valor' => 'USULUTÁN',
                'departamento' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 12
            [
                'codigo' => '01',
                'valor' => 'CAROLINA',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'CIUDAD BARRIOS',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'COMACARÁN',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'CHAPELTIQUE',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'CHINAMECA',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'CHIRILAGUA',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'EL TRANSITO',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'LOLOTIQUE',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'MONCAGUA',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'NUEVA GUADALUPE',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'NVO EDÉN S JUAN',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'QUELEPA',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'SAN ANT D MOSCO',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'SAN GERARDO',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'SAN JORGE',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'SAN LUIS REINA',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17',
                'valor' => 'SAN MIGUEL',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18',
                'valor' => 'SAN RAF ORIENTE',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '19',
                'valor' => 'SESORI',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '20',
                'valor' => 'ULUAZAPA',
                'departamento' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 13
            [
                'codigo' => '01',
                'valor' => 'ARAMBALA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'CACAOPERA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'CORINTO',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'CHILANGA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'DELIC DE CONCEP',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'EL DIVISADERO',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'EL ROSARIO',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'GUALOCOCTI',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'GUATAJIAGUA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'JOATECA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'JOCOAITIQUE',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'JOCORO',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'LOLOTIQUILLO',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'MEANGUERA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'OSICALA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'PERQUÍN',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17',
                'valor' => 'SAN CARLOS',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18',
                'valor' => 'SAN FERNANDO',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '19',
                'valor' => 'SAN FCO GOTERA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '20',
                'valor' => 'SAN ISIDRO',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '21',
                'valor' => 'SAN SIMÓN',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '22',
                'valor' => 'SENSEMBRA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '23',
                'valor' => 'SOCIEDAD',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '24',
                'valor' => 'TOROLA',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '25',
                'valor' => 'YAMABAL',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '26',
                'valor' => 'YOLOAIQUÍN',
                'departamento' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Departamento 14
            [
                'codigo' => '01',
                'valor' => 'ANAMOROS',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '02',
                'valor' => 'BOLÍVAR',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '03',
                'valor' => 'CONCEP DE OTE',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '04',
                'valor' => 'CONCHAGUA',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '05',
                'valor' => 'EL CARMEN',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '06',
                'valor' => 'EL SAUCE',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '07',
                'valor' => 'INTIPUCÁ',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '08',
                'valor' => 'LA UNIÓN',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '09',
                'valor' => 'LISLIQUE',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '10',
                'valor' => 'MEANG DEL GOLFO',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11',
                'valor' => 'NUEVA ESPARTA',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '12',
                'valor' => 'PASAQUINA',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '13',
                'valor' => 'POLORÓS',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14',
                'valor' => 'SAN ALEJO',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15',
                'valor' => 'SAN JOSE',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '16',
                'valor' => 'SANTA ROSA LIMA',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17',
                'valor' => 'YAYANTIQUE',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18',
                'valor' => 'YUCUAIQUÍN',
                'departamento' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('mh_municipio')->insert($values);
    }
}
