<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MHPais extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $values = [
            [
                'codigo' => 'AF',
                'valor' => 'Afganistán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AX',
                'valor' => 'Aland',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AL',
                'valor' => 'Albania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'DE',
                'valor' => 'Alemania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AD',
                'valor' => 'Andorra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AO',
                'valor' => 'Angola',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AI',
                'valor' => 'Anguila',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AQ',
                'valor' => 'Antártida',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AG',
                'valor' => 'Antigua y Barbuda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AW',
                'valor' => 'Aruba',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SA',
                'valor' => 'Arabia Saudita',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'DZ',
                'valor' => 'Argelia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AR',
                'valor' => 'Argentina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AM',
                'valor' => 'Armenia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AU',
                'valor' => 'Australia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AT',
                'valor' => 'Austria',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AZ',
                'valor' => 'Azerbaiyán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BS',
                'valor' => 'Bahamas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BH',
                'valor' => 'Bahréin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BD',
                'valor' => 'Bangladés',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BB',
                'valor' => 'Barbados',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BE',
                'valor' => 'Bélgica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BZ',
                'valor' => 'Belice',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BJ',
                'valor' => 'Benín',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BM',
                'valor' => 'Bermudas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BY',
                'valor' => 'Bielorrusia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BO',
                'valor' => 'Bolivia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BQ',
                'valor' => 'Bonaire, San Eustaquio y Saba',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BA',
                'valor' => 'Bosnia y Herzegovina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BW',
                'valor' => 'Botsuana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BR',
                'valor' => 'Brasil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BN',
                'valor' => 'Brunéi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BG',
                'valor' => 'Bulgaria',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BF',
                'valor' => 'Burkina Faso',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BI',
                'valor' => 'Burundi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BT',
                'valor' => 'Bután',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CV',
                'valor' => 'Cabo Verde',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KY',
                'valor' => 'Islas Caimán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KH',
                'valor' => 'Camboya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CM',
                'valor' => 'Camerún',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CA',
                'valor' => 'Canadá',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CF',
                'valor' => 'República Centroafricana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TD',
                'valor' => 'Chad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CL',
                'valor' => 'Chile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CN',
                'valor' => 'China',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CY',
                'valor' => 'Chipre',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'VA',
                'valor' => 'Ciudad del Vaticano',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CO',
                'valor' => 'Colombia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KM',
                'valor' => 'Comoras',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CG',
                'valor' => 'Congo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CI',
                'valor' => 'Costa de Marfil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CR',
                'valor' => 'Costa Rica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'HR',
                'valor' => 'Croacia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CU',
                'valor' => 'Cuba',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CW',
                'valor' => 'Curazao',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'DK',
                'valor' => 'Dinamarca',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'DM',
                'valor' => 'Dominica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'DJ',
                'valor' => 'Yibuti',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'EC',
                'valor' => 'Ecuador',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'EG',
                'valor' => 'Egipto',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SV',
                'valor' => 'El Salvador',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AE',
                'valor' => 'Emiratos Árabes Unidos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ER',
                'valor' => 'Eritrea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SK',
                'valor' => 'Eslovaquia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SI',
                'valor' => 'Eslovenia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ES',
                'valor' => 'España',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'US',
                'valor' => 'Estados Unidos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'EE',
                'valor' => 'Estonia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ET',
                'valor' => 'Etiopía',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'FJ',
                'valor' => 'Fiyi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PH',
                'valor' => 'Filipinas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'FI',
                'valor' => 'Finlandia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'FR',
                'valor' => 'Francia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GA',
                'valor' => 'Gabón',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GM',
                'valor' => 'Gambia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GE',
                'valor' => 'Georgia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GH',
                'valor' => 'Ghana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GI',
                'valor' => 'Gibraltar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GD',
                'valor' => 'Granada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GR',
                'valor' => 'Grecia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GL',
                'valor' => 'Groenlandia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GP',
                'valor' => 'Guadalupe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GU',
                'valor' => 'Guam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GT',
                'valor' => 'Guatemala',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GF',
                'valor' => 'Guayana Francesa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GG',
                'valor' => 'Guernsey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GN',
                'valor' => 'Guinea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GQ',
                'valor' => 'Guinea Ecuatorial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GW',
                'valor' => 'Guinea-Bisáu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GY',
                'valor' => 'Guinea-Bisáu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'HT',
                'valor' => 'Haití',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'HN',
                'valor' => 'Honduras',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'HK',
                'valor' => 'Hong Kong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'HU',
                'valor' => 'Hungría',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IN',
                'valor' => 'India',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ID',
                'valor' => 'Indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IQ',
                'valor' => 'Irak',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IE',
                'valor' => 'Irlanda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BV',
                'valor' => 'Isla Bouvet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IM',
                'valor' => 'Isla de Man',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NF',
                'valor' => 'Isla Norfolk',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IS',
                'valor' => 'Islandia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CX',
                'valor' => 'Isla de Navidad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CC',
                'valor' => 'Islas Cocos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CK',
                'valor' => 'Islas Cook',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'FO',
                'valor' => 'Islas Feroe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GS',
                'valor' => 'Islas Georgia del Sur y Sandwich del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'HM',
                'valor' => 'Islas Heard y McDonald',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'FK',
                'valor' => 'Islas Malvinas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MP',
                'valor' => 'Islas Marianas del Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MH',
                'valor' => 'Islas Marshall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PN',
                'valor' => 'Islas Pitcairn',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TC',
                'valor' => 'Islas Turcas y Caicos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'UM',
                'valor' => 'Islas Ultramarinas Menores de Estados Unidos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'VI',
                'valor' => 'Islas Vírgenes de los Estados Unidos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IL',
                'valor' => 'Israel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IT',
                'valor' => 'Italia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'JM',
                'valor' => 'Jamaica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'JP',
                'valor' => 'Japón',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'JE',
                'valor' => 'Jersey',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'JO',
                'valor' => 'Jordania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KZ',
                'valor' => 'Kazajistán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KE',
                'valor' => 'Kenia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KG',
                'valor' => 'Kirguistán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KI',
                'valor' => 'Kiribati',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KW',
                'valor' => 'Kuwait',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LA',
                'valor' => 'Laos, República Democrática',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LS',
                'valor' => 'Lesoto',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LV',
                'valor' => 'Letonia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LB',
                'valor' => 'Líbano',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LR',
                'valor' => 'Liberia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LY',
                'valor' => 'Libia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LI',
                'valor' => 'Liechtenstein',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LT',
                'valor' => 'Lituania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LU',
                'valor' => 'Luxemburgo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MO',
                'valor' => 'Macao',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MK',
                'valor' => 'Macedonia del Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MG',
                'valor' => 'Madagascar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MY',
                'valor' => 'Malasia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MW',
                'valor' => 'MalaWi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MV',
                'valor' => 'Maldivas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ML',
                'valor' => 'Malí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MT',
                'valor' => 'Malta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MA',
                'valor' => 'Marruecos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MQ',
                'valor' => 'Martinica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MU',
                'valor' => 'Mauricio',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MR',
                'valor' => 'Mauritania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'YT',
                'valor' => 'Mayotte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MX',
                'valor' => 'México',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'FM',
                'valor' => 'Micronesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MD',
                'valor' => 'Moldavia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MC',
                'valor' => 'Mónaco',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MN',
                'valor' => 'Mongolia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ME',
                'valor' => 'Montenegro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MS',
                'valor' => 'Montserrat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MZ',
                'valor' => 'Mozambique',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MM',
                'valor' => 'Myanmar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NA',
                'valor' => 'Namibia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NR',
                'valor' => 'Nauru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NP',
                'valor' => 'Nepal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NI',
                'valor' => 'Nicaragua',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NE',
                'valor' => 'Níger',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NG',
                'valor' => 'Nigeria',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NU',
                'valor' => 'Niue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NO',
                'valor' => 'Noruega',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NC',
                'valor' => 'Nueva Caledonia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NZ',
                'valor' => 'Nueva Zelanda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'OM',
                'valor' => 'Omán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'NL',
                'valor' => 'Países Bajos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PK',
                'valor' => 'Pakistán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PW',
                'valor' => 'Palaos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PS',
                'valor' => 'Palestina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PA',
                'valor' => 'Panamá',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PG',
                'valor' => 'Papúa Nueva Guinea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PY',
                'valor' => 'Paraguay',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PE',
                'valor' => 'Perú',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PF',
                'valor' => 'Polinesia Francesa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PL',
                'valor' => 'Polonia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PT',
                'valor' => 'Portugal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PR',
                'valor' => 'Puerto Rico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'QA',
                'valor' => 'Qatar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'GB',
                'valor' => 'Reino Unido',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KP',
                'valor' => 'República Popular Democrática de Corea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CZ',
                'valor' => 'República Checa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KR',
                'valor' => 'República de Corea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CD',
                'valor' => 'República Democrática del Congo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'DO',
                'valor' => 'República Dominicana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IR',
                'valor' => 'Republica islamica de Iran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'RE',
                'valor' => 'Reunión',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'RW',
                'valor' => 'Ruanda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'RO',
                'valor' => 'Rumanía',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'RU',
                'valor' => 'Rusia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'EH',
                'valor' => 'Sahara Occidental',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'BL',
                'valor' => 'San Bartolomé',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'MF',
                'valor' => 'San Martín',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SB',
                'valor' => 'Islas Salomón',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'WS',
                'valor' => 'Samoa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'AS',
                'valor' => 'Samoa Americana',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'KN',
                'valor' => 'San Cristóbal y Nieves',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SM',
                'valor' => 'San Marino',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PM',
                'valor' => 'San Pedro y Miquelón',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'VC',
                'valor' => 'San Vicente y las Granadinas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SH',
                'valor' => 'Santa Elena, Ascensión y Tristán de Acuña',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LC',
                'valor' => 'Santa Lucía',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ST',
                'valor' => 'Santo Tomé y Príncipe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SN',
                'valor' => 'Senegal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'RS',
                'valor' => 'Serbia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SC',
                'valor' => 'Seychelles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SL',
                'valor' => 'Sierra Leona',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SG',
                'valor' => 'Singapur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SX',
                'valor' => 'Sint Maarten',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SY',
                'valor' => 'Siria',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SO',
                'valor' => 'Somalia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SS',
                'valor' => 'Sudán del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'LK',
                'valor' => 'Sri Lanka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ZA',
                'valor' => 'Sudáfrica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SD',
                'valor' => 'Sudán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SE',
                'valor' => 'Suecia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'CH',
                'valor' => 'Suiza',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SR',
                'valor' => 'Surinam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SJ',
                'valor' => 'Svalbard y Jan Mayen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'SZ',
                'valor' => 'Suazilandia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TH',
                'valor' => 'Tailandia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TW',
                'valor' => 'Taiwán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TZ',
                'valor' => 'Tanzania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TJ',
                'valor' => 'Tayikistán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'IO',
                'valor' => 'Territorio Británico del Océano Índico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TF',
                'valor' => 'Territorios Australes Franceses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TL',
                'valor' => 'Timor Oriental',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TG',
                'valor' => 'Togo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TK',
                'valor' => 'Tokelau',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TO',
                'valor' => 'Tonga',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TT',
                'valor' => 'Trinidad y Tobago',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TN',
                'valor' => 'Túnez',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TM',
                'valor' => 'Turkmenistán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TR',
                'valor' => 'Turquía',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'TV',
                'valor' => 'Tuvalu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'UA',
                'valor' => 'Ucrania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'UG',
                'valor' => 'Uganda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'UY',
                'valor' => 'Uruguay',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'UZ',
                'valor' => 'Uzbekistán',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'VU',
                'valor' => 'Vanuatu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'VE',
                'valor' => 'Venezuela',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'VN',
                'valor' => 'Vietnam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'VG',
                'valor' => 'Islas Vírgenes Británicas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'WF',
                'valor' => 'Wallis y Futuna',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'YE',
                'valor' => 'Yemen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ZM',
                'valor' => 'Zambia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'ZW',
                'valor' => 'Zimbabue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ];

        DB::table('mh_pais')->insert($values);
    }
}
